export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_USER_TOKEN = "SET_USER_TOKEN";

export const TEST_ACTION = "TEST_ACTION";

export const SHOW_EDITOR = "SHOW_EDITOR";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SELECT_ALL = "SELECT_ALL";
export const SELECT_STARRED = "SELECT_STARRED";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SELECT_SNIPPET = "SELECT_SNIPPET";
export const RESET_SELECT_SNIPPET = "RESET_SELECT-SNIPPET";
export const SHOW_COPIED_INFO = "SHOW_COPIED_INFO";
export const COPY_EVENT = "COPY_EVENT";

export const SAVE_SNIPPET = "SAVE_SNIPPET";

export const UPDATE_FORM_VALUES = "UPDATE_FORM_VALUES";
export const CLEAR_FORM = "CLEAR_FORM";
export const SET_ALL_FORM_VALUES = "SET_ALL_FORM_VALUES";
